blank_issues_enabled: false
contact_links:
  - name: Faça uma pergunta
    url: https://github.com/rramoscabral/M365SharePointPT/discussions
    about: Faça perguntas e discuta com outros membros da comunidade
